POST http://localhost:1947/login
Content-Type: application/json

{
    "username": "azif",
    "password": "123456"
}

###

GET http://localhost:1947/bye

###

GET http://localhost:1947/

###

POST http://localhost:1947/register
Content-Type: application/json

{
    "username": "UTEM",
    "password": "utemdabest",
    "name": "UTeM",
    "email": "b022110210@student.utem.edu.my"
}

###

POST http://localhost:1947/login
Content-Type: application/json

{
    "username": "UTEM",
    "password": "utemdabest"
}

###

GET http://localhost:1947/bye
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6aWYiLCJwYXNzd29yZCI6IjEyMzQ1NiIsIm5hbWUiOiJBemlmIiwiZW1haWwiOiJhemlmZmFyaGFuMTk0N0BnbWFpbC5jb20iLCJpYXQiOjE2ODEzNzIyMDUsImV4cCI6MTY4MTM3MjI2NX0.zX1Ke_LtA8JcwGGYRa4dQuJrJfs_nnlgJVxwa9fzXbI



