POST http://localhost:1947/login
Content-Type: application/json

{
    "username": "azif",
    "password": "123456"
}

###

GET http://localhost:1947/bye

###

GET http://localhost:1947/

###

POST http://localhost:1947/register
Content-Type: application/json

{
    "username": "UTEM",
    "password": "utemdabest",
    "name": "UTeM",
    "email": "b022110210@student.utem.edu.my"
}

###

POST http://localhost:1947/login
Content-Type: application/json

{
    "username": "UTEM",
    "password": "utemdabest"
}